### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by Yingxiu-Chang** [TomRoussel/DepthEstimationTensorFlow#3]
Hi Tom @TomRoussel, 
Do you have any trained model with weights so that I can test single image? 
All the best
Yingxiu

**Comment by TomRoussel** [comment]
Sorry, I do not have any pretrained weights available for this project. Also, this repository is very outdated and not maintained, I recommend you look at other depth estimation implementations/architectures.
This repository has a pretty good implementation, with weights available:
https://github.com/OniroAI/MonoDepth-PyTorch

Good luck with your search!
